import { Link, NavLink } from 'react-router-dom';
import { ArrowUpRight, Heart, Globe2, House, ChevronRight, LoaderCircle, ArrowLeft } from 'lucide-react';
import { Button } from './ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';

export const Logo = ({light=false,id='brand-home'}) => <Link to="/" className={`logo ${light?'light':''}`} data-testid={id}><span className="logo-symbol"><House strokeWidth={1.8} size={24}/></span>AuraStay<span className="brand-dot">.</span></Link>;
export const GuestHeader = () => <header className="guest-header"><div className="header-inner"><Logo/><nav className="guest-nav" aria-label="Main navigation"><NavLink to="/" end data-testid="nav-explore">Explore stays</NavLink><NavLink to="/saved" data-testid="nav-saved"><Heart size={15}/> Saved stays</NavLink></nav><div className="header-actions"><span className="currency" data-testid="currency-eur"><Globe2 size={16}/> EUR €</span><Link className="workspace-link" to="/workspace" data-testid="agency-workspace-link">Agency workspace <ArrowUpRight size={16}/></Link></div></div></header>;
export const Footer = () => <footer className="guest-footer"><div><Logo id="footer-brand-home"/><span data-testid="footer-tagline">Good places. Great possibilities.</span></div><div><span data-testid="footer-copyright">© {new Date().getFullYear()} AuraStay</span><span data-testid="footer-currency">All prices in EUR</span><Link to="/login" data-testid="footer-partner-link">Partner workspace <ArrowUpRight size={14}/></Link></div></footer>;
export const Action = ({children,id,variant='default',...props}) => <Button data-testid={id} variant={variant} {...props}>{children}</Button>;
export const Field = ({label,id,children,wide=false,...props}) => <label className={`field ${wide?'wide':''}`} htmlFor={id}><span data-testid={`${id}-label`}>{label}</span>{children || <input id={id} data-testid={id} {...props}/>}</label>;
export const Select = ({label,id,children,...props}) => <Field label={label} id={id}><select id={id} data-testid={id} {...props}>{children}</select></Field>;
export const Modal = ({open,onClose,title,description,children,wide=false}) => <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`app-modal ${wide?'wide-modal':''}`} data-testid="active-modal"><DialogTitle data-testid="modal-title">{title}</DialogTitle><DialogDescription data-testid="modal-description">{description || ' '}</DialogDescription>{children}</DialogContent></Dialog>;
export const Loading = () => <div className="loading" data-testid="loading-state"><LoaderCircle className="spin" size={26}/><span>Finding your next good place…</span></div>;
export const Empty = ({title='Nothing here yet',text,children}) => <div className="empty-state" data-testid="empty-state"><House size={30}/><h3 data-testid="empty-title">{title}</h3>{text&&<p data-testid="empty-description">{text}</p>}{children}</div>;
export const Badge = ({value,id}) => <span data-testid={id} className={`badge badge-${value}`}>{String(value).replaceAll('_',' ')}</span>;
export const PageHeading = ({eyebrow,title,description,children}) => <div className="page-heading"><div>{eyebrow&&<span className="eyebrow" data-testid="page-eyebrow">{eyebrow}</span>}<h1 data-testid="page-title">{title}</h1>{description&&<p data-testid="page-description">{description}</p>}</div><div className="heading-actions">{children}</div></div>;
export const BackLink = () => <Link to="/" className="back-link" data-testid="back-to-stays"><ArrowLeft size={16}/> Back to stays</Link>;
export const Breadcrumb = ({name}) => <div className="breadcrumb" data-testid="breadcrumb"><Link to="/" data-testid="breadcrumb-stays">Explore stays</Link><ChevronRight size={13}/><span>{name}</span></div>;