import { useEffect,useState,useCallback } from 'react';
import { Trash2,Plus,CalendarDays } from 'lucide-react';
import { Modal,Field,Select,Action,Empty } from './common';
import { api,errorMessage,dateLabel } from '../lib/api';
import { useWorkspace } from '../pages/Workspace';
import { toast } from './ui/sonner';
export default function PropertyCalendar({property,onClose}){
  const {canWrite}=useWorkspace();const [data,setData]=useState({blocks:[],reservations:[]});const [form,setForm]=useState({check_in:'',check_out:'',kind:'maintenance',reason:''});const [busy,setBusy]=useState(false);
  const load=useCallback(()=>property&&api.get(`/workspace/properties/${property.id}/calendar`).then(r=>setData(r.data)).catch(e=>toast.error(errorMessage(e))),[property]);useEffect(()=>{if(property){load();setForm({check_in:'',check_out:'',kind:'maintenance',reason:''})}},[property,load]);
  async function add(e){e.preventDefault();setBusy(true);try{await api.post(`/workspace/properties/${property.id}/blocks`,form);load();setForm({...form,reason:''});toast.success('Calendar updated')}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
  async function remove(id){try{await api.delete(`/workspace/blocks/${id}`);load();toast.success('Dates released')}catch(e){toast.error(errorMessage(e))}}
  return <Modal open={!!property} onClose={onClose} title="A little room in the calendar" description={property?.name} wide><div className="calendar-list">{data.reservations.map(b=><div key={b.id} data-testid={`calendar-reservation-${b.id}`}><CalendarDays size={17}/><div><strong>{dateLabel(b.check_in)} — {dateLabel(b.check_out)}</strong><span>{b.guest_name} · {b.status}</span></div><span className="badge badge-confirmed">Reserved</span></div>)}{data.blocks.map(b=><div key={b.id} data-testid={`calendar-block-${b.id}`}><CalendarDays size={17}/><div><strong>{dateLabel(b.check_in)} — {dateLabel(b.check_out)}</strong><span>{b.reason} · {b.kind}</span></div>{canWrite&&<Action id={`remove-block-${b.id}`} size="icon" variant="ghost" title="Release these dates" onClick={()=>remove(b.id)}><Trash2 size={15}/></Action>}</div>)}{!data.blocks.length&&!data.reservations.length&&<Empty title="An open calendar"/>}</div>{canWrite&&<form className="form-stack" onSubmit={add}><h3 data-testid="add-block-title">Keep these dates aside</h3><div className="form-grid"><Field label="From" id="block-check-in" type="date" required value={form.check_in} onChange={e=>setForm({...form,check_in:e.target.value})}/><Field label="Until (departure)" id="block-check-out" type="date" required min={form.check_in} value={form.check_out} onChange={e=>setForm({...form,check_out:e.target.value})}/><Select label="Reason category" id="block-kind" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="maintenance">Maintenance</option><option value="owner">Owner stay</option><option value="external">External reservation</option></Select><Field label="Description" id="block-reason" required minLength={2} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><Action id="save-calendar-block" type="submit" disabled={busy}><Plus size={15}/>Block dates</Action></form>}</Modal>;
}