import { useEffect,useState } from 'react';
import { Plus, Search, Pencil, CalendarDays, ArrowUpRight, Building2, Users, BedDouble } from 'lucide-react';
import { PageHeading,Action,Badge,Loading,Empty } from '../../components/common';
import { ErrorNotice,SecureImage,ScopeNotice } from '../../components/workspace-ui';
import { useWorkspace } from '../Workspace';
import { api,euro,errorMessage } from '../../lib/api';
import PropertyEditor from '../../components/PropertyEditor';
import PropertyCalendar from '../../components/PropertyCalendar';
export default function Properties(){
  const {canWrite}=useWorkspace();const [rows,setRows]=useState(null);const [error,setError]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [editing,setEditing]=useState(null);const [calendar,setCalendar]=useState(null);
  const load=()=>api.get('/workspace/properties').then(r=>setRows(r.data)).catch(e=>setError(errorMessage(e)));useEffect(()=>{load()},[]);
  const filtered=(rows||[]).filter(p=>(!status||p.status===status)&&`${p.name} ${p.city}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeading eyebrow="YOUR COLLECTION" title="Places with possibility." description="A little care turns a property into someone's favourite place."><Action id="add-property" disabled={!canWrite} onClick={()=>setEditing({})}><Plus size={17}/>Add property</Action></PageHeading>{!canWrite&&<ScopeNotice/>}<div className="table-controls"><div className="control-search"><Search size={16}/><input data-testid="workspace-property-search" aria-label="Search properties" placeholder="Find a property…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select data-testid="workspace-property-status" aria-label="Property status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All properties</option><option value="published">Published</option><option value="draft">Drafts</option><option value="archived">Archived</option></select><span data-testid="workspace-property-count">{filtered.length} properties</span></div><ErrorNotice error={error}/>{!rows?<Loading/>:!filtered.length?<Empty title="Room for something new" text="Your next great property belongs here."/>:<div className="managed-property-grid">{filtered.map(p=><article className="managed-property" key={p.id} data-testid={`managed-property-${p.id}`}><div className="managed-property-image">{p.photos[0]?<SecureImage src={p.photos[0]} alt={p.name}/>:<Building2 size={36}/>}<Badge value={p.status} id={`managed-property-status-${p.id}`}/></div><div className="managed-property-body"><span className="eyebrow" data-testid={`managed-location-${p.id}`}>{p.city}, {p.country}</span><h3 data-testid={`managed-name-${p.id}`}>{p.name}</h3><p className="managed-specs" data-testid={`managed-specs-${p.id}`}><Users size={14}/>{p.guests} guests<span>·</span><BedDouble size={14}/>{p.bedrooms} beds</p><div className="managed-price-row"><span data-testid={`managed-price-${p.id}`}><strong>{euro(p.price,false)}</strong> / night</span><span data-testid={`managed-rate-${p.id}`}>{p.commission_rate}% agency rate</span></div><div className="managed-property-actions"><Action id={`edit-property-${p.id}`} variant="outline" disabled={!canWrite} onClick={()=>setEditing(p)}><Pencil size={14}/>Edit property</Action><Action id={`calendar-property-${p.id}`} variant="ghost" onClick={()=>setCalendar(p)} title="Manage calendar"><CalendarDays size={17}/></Action>{p.status==='published'&&<a href={`/stays/${p.id}`} target="_blank" rel="noreferrer" data-testid={`preview-property-${p.id}`} title="View listing"><ArrowUpRight size={18}/></a>}</div></div></article>)}</div>}<PropertyEditor property={editing} onClose={()=>setEditing(null)} onSave={()=>{setEditing(null);load()}}/><PropertyCalendar property={calendar} onClose={()=>setCalendar(null)}/></>;
}