import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Search, MapPin, CalendarDays, Users, SlidersHorizontal, ArrowUpRight, Heart, House, Waves, Building2, Trees, LayoutGrid, ShieldCheck, KeyRound, ArrowRight, X } from 'lucide-react';
import { GuestHeader, Footer, Action, Modal, Loading, Empty, Field } from '../components/common';
import { api, euro, errorMessage, photoUrl, today } from '../lib/api';

const categories=[['','All stays',LayoutGrid],['Coastal','By the coast',Waves],['Villas','Villas & retreats',House],['City breaks','City escapes',Building2],['Countryside','Countryside',Trees]];
const amenities=['Wi-Fi','Pool','Free parking','Air conditioning','Kitchen','Garden','Workspace','Balcony'];
const readSaved=()=>{try{return JSON.parse(localStorage.getItem('aurastay-saved')||'[]')}catch{return []}};
export default function Catalogue({savedOnly=false}) {
  const [params,setParams]=useSearchParams();
  const [search,setSearch]=useState({destination:params.get('destination')||'',check_in:params.get('check_in')||'',check_out:params.get('check_out')||'',guests:params.get('guests')||1});
  const [category,setCategory]=useState(''); const [sort,setSort]=useState('recommended');
  const [filters,setFilters]=useState({max_price:1000,amenities:[]});const [draft,setDraft]=useState(filters);
  const [filterOpen,setFilterOpen]=useState(false);const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saved,setSaved]=useState(readSaved);
  useEffect(()=>{let live=true;setLoading(true);setError('');api.get('/properties',{params:{...Object.fromEntries(params),category,sort,max_price:filters.max_price,amenities:filters.amenities.join(',')}}).then(r=>live&&setRows(r.data.properties)).catch(e=>live&&setError(errorMessage(e))).finally(()=>live&&setLoading(false));return()=>{live=false}},[params,category,sort,filters]);
  const submit=e=>{e.preventDefault();if(!!search.check_in!==!!search.check_out){setError('Please select both check-in and check-out dates.');return}setParams(Object.fromEntries(Object.entries(search).filter(([,v])=>v)))};
  const toggleSaved=id=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('aurastay-saved',JSON.stringify(next))};
  const displayed=rows.filter(p=>!savedOnly||saved.includes(p.id));
  return <><GuestHeader/><main className="catalogue page-container" data-testid="guest-property-catalogue">
    <section className="catalogue-intro"><div><div className="eyebrow" data-testid="catalogue-eyebrow"><span className="little-line"/> A GOOD PLACE TO BE</div><h1 data-testid="catalogue-title">Find your kind of <span>somewhere.</span></h1><p data-testid="catalogue-subtitle">Thoughtfully chosen homes. Local expertise. A stay that feels like you.</p></div><div className="intro-note" data-testid="catalogue-note"><span className="note-icon"><KeyRound size={20}/></span><div>More than a place to stay.<br/><strong>A place to feel at home.</strong></div></div></section>
    <form className="search-bar" onSubmit={submit} data-testid="stay-search-form">
      <label className="search-field destination"><MapPin size={19}/><div><span>Where to?</span><input aria-label="Destination" data-testid="search-destination" placeholder="City, region or country" value={search.destination} onChange={e=>setSearch({...search,destination:e.target.value})}/></div></label>
      <label className="search-field"><CalendarDays size={19}/><div><span>Check-in</span><input aria-label="Check-in" data-testid="search-check-in" type="date" min={today()} value={search.check_in} onChange={e=>setSearch({...search,check_in:e.target.value})}/></div></label>
      <label className="search-field"><CalendarDays size={19}/><div><span>Check-out</span><input aria-label="Check-out" data-testid="search-check-out" type="date" min={search.check_in||today()} value={search.check_out} onChange={e=>setSearch({...search,check_out:e.target.value})}/></div></label>
      <label className="search-field guest-count"><Users size={19}/><div><span>Guests</span><select aria-label="Guests" data-testid="search-guests" value={search.guests} onChange={e=>setSearch({...search,guests:e.target.value})}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{`${i+1} guest${i?'s':''}`}</option>)}</select></div></label>
      <Action className="search-button" id="search-stays-button" type="submit"><Search size={18}/><span>Search stays</span></Action>
    </form>
    <div className="discovery-toolbar"><div className="category-tabs" role="tablist">{categories.map(([key,label,Icon])=><button role="tab" aria-selected={category===key} className={category===key?'active':''} data-testid={`category-${key||'all'}`} key={key} onClick={()=>setCategory(key)}><Icon size={20}/>{label}</button>)}</div><Action id="open-filters" variant="outline" className="filter-button" onClick={()=>{setDraft(filters);setFilterOpen(true)}}><SlidersHorizontal size={16}/>Filters{filters.amenities.length>0&&<span className="filter-count">{filters.amenities.length}</span>}</Action></div>
    <div className="results-header"><div><h2 data-testid="results-title">{savedOnly?'Your saved places':category?categories.find(c=>c[0]===category)?.[1]:'A little inspiration for your next chapter'}</h2><span data-testid="property-count">{loading?'Looking for great places…':`${displayed.length} beautiful ${displayed.length===1?'place':'places'} to make your own`}</span></div><div className="sort-control"><span>Sort by:</span><select data-testid="price-sort" aria-label="Sort properties" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></div></div>
    {error?<div className="error-banner" role="alert" data-testid="catalogue-error">{error}</div>:loading?<Loading/>:displayed.length===0?<Empty title={savedOnly?'A few favourites, all in one place':'No stays found'} text={savedOnly?'Save a place that catches your eye.':'Try another destination or adjust your filters.'}><Action id="clear-filters" variant="outline" onClick={()=>{setCategory('');setFilters({max_price:1000,amenities:[]});setParams({});setSearch({destination:'',check_in:'',check_out:'',guests:1})}}>Reset search</Action></Empty>:<div className="property-grid">{displayed.map((p,i)=><article className="property-card" key={p.id} data-testid={`property-card-${p.id}`} style={{animationDelay:`${i*55}ms`}}><div className="property-image-wrap"><Link to={`/stays/${p.id}?${params.toString()}`} data-testid={`property-image-${p.id}`}><img src={photoUrl(p.photos[0])} alt={p.name} loading={i<4?'eager':'lazy'}/></Link><span className="property-category" data-testid={`property-type-${p.id}`}>{p.type==='Villa'?'Room to unwind':p.category==='Coastal'?'Coastal living':p.type==='Penthouse'?'Above it all':'A local favourite'}</span><button className={`save-button ${saved.includes(p.id)?'is-saved':''}`} data-testid={`save-property-${p.id}`} aria-label={saved.includes(p.id)?'Unsave property':'Save property'} onClick={()=>toggleSaved(p.id)}><Heart size={18} fill={saved.includes(p.id)?'currentColor':'none'}/></button><span className="image-dots"><i/><i/><i/></span></div><div className="property-card-body"><div className="location-line" data-testid={`property-location-${p.id}`}><MapPin size={12}/>{p.city}, {p.country}<span>{p.type}</span></div><Link to={`/stays/${p.id}?${params.toString()}`} data-testid={`property-title-${p.id}`}><h3>{p.name}</h3></Link><p className="property-specs" data-testid={`property-specs-${p.id}`}>{p.guests} guests <i/> {p.bedrooms} bedroom{p.bedrooms!==1?'s':''} <i/> {p.amenities.includes('Pool')?'Private pool':p.amenities.includes('Balcony')?'Balcony':'Garden'}</p><div className="property-bottom"><div data-testid={`property-price-${p.id}`}><strong>{euro(p.price,false)}</strong><span> / night</span></div><Link to={`/stays/${p.id}?${params.toString()}`} aria-label={`View ${p.name}`} className="view-stay-link" data-testid={`view-property-${p.id}`}><ArrowUpRight size={18}/></Link></div></div></article>)}</div>}
    <div className="trust-strip"><div><ShieldCheck size={23}/><p data-testid="trust-agencies"><strong>In good hands</strong><span>Homes managed by local agencies</span></p></div><div><House size={23}/><p data-testid="trust-properties"><strong>All the space, just for you</strong><span>Entire homes. Your own little world.</span></p></div><div><KeyRound size={23}/><p data-testid="trust-pricing"><strong>A little fee. A clear beginning.</strong><span>Reservation fee shown before you pay</span></p></div><ArrowRight size={26} className="trust-arrow"/></div>
  </main><Footer/><Modal open={filterOpen} onClose={()=>setFilterOpen(false)} title="Make it your kind of stay" description="A few details make all the difference."><div className="filters-body"><Field label={`Maximum nightly price · ${euro(draft.max_price,false)}`} id="filter-max-price" type="range" min="50" max="1000" step="10" value={draft.max_price} onChange={e=>setDraft({...draft,max_price:Number(e.target.value)})}/><h3 data-testid="filter-amenities-title">The little essentials</h3><div className="amenity-options">{amenities.map(a=><label key={a}><input type="checkbox" data-testid={`filter-amenity-${a.replaceAll(' ','-')}`} checked={draft.amenities.includes(a)} onChange={()=>setDraft({...draft,amenities:draft.amenities.includes(a)?draft.amenities.filter(x=>x!==a):[...draft.amenities,a]})}/>{a}</label>)}</div></div><div className="modal-actions"><Action id="reset-filter-options" variant="ghost" onClick={()=>setDraft({max_price:1000,amenities:[]})}>Reset</Action><Action id="apply-filters" onClick={()=>{setFilters(draft);setFilterOpen(false)}}>Show stays <ArrowRight size={16}/></Action></div></Modal></>;
}