import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowRight, LockKeyhole } from 'lucide-react';
import { Logo, Field, Action } from '../components/common';
import { api, errorMessage } from '../lib/api';
export default function Login(){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();
  async function login(e){e.preventDefault();setBusy(true);setError('');try{localStorage.removeItem('aurastay-agency');const {data}=await api.post('/auth/login',{email,password});localStorage.setItem('aurastay-token',data.token);navigate('/workspace')}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  return <div className="login-page"><div className="login-top"><Logo/><Link data-testid="login-back-marketplace" to="/">Back to stays <ArrowRight size={16}/></Link></div><main className="login-main"><div className="login-heading"><div className="login-icon"><LockKeyhole size={24}/></div><span className="eyebrow" data-testid="login-eyebrow">THE PARTNER WORKSPACE</span><h1 data-testid="login-title">Good to have you back.</h1><p data-testid="login-subtitle">Your properties, people and possibilities. All in one place.</p></div><form onSubmit={login} className="login-form"><Field label="Email address" id="login-email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@youragency.com"/><Field label="Password" id="login-password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/>{error&&<div role="alert" className="error-banner" data-testid="login-error">{error}</div>}<Action id="login-submit" type="submit" disabled={busy}>{busy?'Signing in…':'Enter your workspace'}<ArrowRight size={17}/></Action></form><p className="login-help" data-testid="login-access-note">For access or password changes, contact your platform administrator.</p></main><div className="login-bottom" data-testid="login-footer">A little less admin. A little more possibility.</div></div>;
}